title: Slinker Animation Studios
description: Original animation, illustration, and storytelling.
url: "https://jslinker.github.io"
baseurl: "/slinker-animation-studios"

markdown: kramdown

exclude:
  - README.md

collections:
  projects:
    output: true
